#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Coarsen sound classes"""


class Coarsen(object):
    remove = {'advanced', 'advanced-tongue-root', 'apical', 'aspirated', 'breathy',
              'centralized', 'creaky', 'ejective', 'glottalized', 'labialized',
              'labio-palatalized', 'laminal', 'less-rounded', 'long', 'lowered',
              'mid-centralized', 'mid-long', 'more-rounded', 'nasalized', 'non-syllabic',
              'palatalized', 'pharyngealized', 'pre-aspirated', 'pre-glottalized',
              'pre-labialized', 'pre-nasalized', 'pre-palatalized', 'primary-stress',
              'raised', 'retracted', 'retracted-tongue-root', 'rhotacized',
              'secondary-stress', 'strong', 'syllabic', 'ultra-long', 'ultra-short',
              'unreleased', 'velarized', 'with-frication', 'with-lateral-release',
              'with-mid-central-vowel-release', 'with-nasal-release', 'with_downstep',
              'with_extra-high_tone', 'with_extra-low_tone', 'with_falling_tone',
              'with_global_fall', 'with_global_rise', 'with_high_tone', 'with_low_tone',
              'with_mid_tone', 'with_rising_tone', 'with_upstep'}

    change = {'alveolar': 'anterior', 'alveolo-palatal': 'palatal', 'close-mid': 'mid',
              'dental': 'anterior', 'linguolabial': 'labial', 'nasal-click': 'click',
              'near-back': 'back', 'near-close': 'close', 'near-front': 'front',
              'near-open': 'open', 'open-mid': 'mid', 'palatal-velar': 'velar',
              'post-alveolar': 'palatal', 'tap': 'vibrant', 'trill': 'vibrant',
              # Taken from "remove"
              'revoiced': 'voiced',
              'devoiced': 'voiceless'}

    coarsened = {'affricate consonant labio-dental voiceless': 'pf',
                 'consonant labial nasal voiced': 'n̼',
                 'consonant labial stop voiced': 'd̼',
                 'consonant labial stop voiceless': 't̼',
                 'consonant labial vibrant voiced': 'ɾ̼',
                 'consonant fricative labial voiceless': 'θ̼',
                 'consonant fricative labial voiced': 'ð̼',
                 'click consonant labial voiced': 'ʇ̼',
                 'approximant consonant labial lateral voiced': 'l̼',
                 'consonant fricative labial lateral voiceless': 'ɬ̼',
                 'consonant fricative labial lateral voiced': 'ɮ̼',
                 'consonant implosive retroflex voiced': 'ᶑ',
                 'consonant labio-dental stop voiced': 'b̪',
                 'consonant labio-dental stop voiceless': 'p̪',
                 'anterior consonant stop voiced': 'd',
                 'anterior approximant consonant lateral voiced': 'l',
                 'anterior consonant nasal voiced': 'n',
                 'anterior consonant vibrant voiced': 'ɾ',
                 'anterior consonant fricative sibilant voiceless': 's',
                 'anterior consonant fricative sibilant voiced': 'z',
                 'affricate anterior consonant lateral voiced': 'dɮ',
                 'affricate anterior consonant sibilant voiced': 'ʣ',
                 'affricate anterior consonant lateral voiceless': 'ƛ',
                 'affricate anterior consonant sibilant voiceless': 'ʦ',
                 'anterior approximant consonant voiced': 'ɹ',
                 'anterior approximant consonant lateral voiced voiceless': 'l̥',
                 'anterior click consonant voiced': 'gǃ',
                 'anterior click consonant voiceless': 'ǃ',
                 'anterior consonant fricative lateral voiced': 'ɮ',
                 'anterior consonant fricative sibilant voiced voiceless': 'z̥',
                 'anterior consonant fricative lateral voiceless': 'ɬ',
                 'anterior consonant nasal voiced voiceless': 'n̊',
                 'anterior consonant stop voiced voiceless': 'd̥',
                 'anterior consonant stop voiceless': 't',
                 'anterior consonant lateral vibrant voiced': 'ɺ',
                 'anterior consonant vibrant voiced voiceless': 'ɾ̥',
                 'anterior click consonant voiced voiceless': 'ŋ̊ǃ',
                 'consonant palatal stop voiceless': 'ȶ',
                 'consonant palatal stop voiced': 'ȡ',
                 'affricate consonant palatal sibilant voiced': 'ʥ',
                 'affricate consonant palatal sibilant voiceless': 'ʨ',
                 'approximant consonant lateral palatal voiced': 'ȴ',
                 'consonant fricative palatal sibilant voiced': 'ʑ',
                 'consonant fricative palatal sibilant voiceless': 'ɕ',
                 'consonant nasal palatal voiced': 'ȵ',
                 'consonant nasal palatal voiced voiceless': 'ȵ̊',
                 'bilabial consonant stop voiced': 'b',
                 'bilabial consonant nasal voiced': 'm',
                 'bilabial consonant stop voiceless': 'p',
                 'affricate bilabial consonant voiced': 'bβ',
                 'affricate bilabial consonant voiceless': 'pɸ',
                 'approximant bilabial consonant voiced': 'β̞',
                 'bilabial consonant fricative voiced': 'β',
                 'bilabial consonant fricative voiceless': 'ɸ',
                 'bilabial consonant implosive voiced': 'ɓ',
                 'bilabial consonant nasal voiced voiceless': 'm̥',
                 'bilabial consonant stop voiced voiceless': 'p̬',
                 'bilabial consonant vibrant voiced': 'ʙ',
                 'bilabial consonant vibrant voiced voiceless': 'ʙ̥',
                 'affricate anterior consonant voiced': 'd̪ð',
                 'affricate anterior consonant voiceless': 'tθ',
                 'anterior consonant fricative voiced': 'ð',
                 'anterior consonant fricative voiceless': 'θ',
                 'anterior consonant fricative voiced voiceless': 'θ̬',
                 'anterior consonant implosive voiced': 'ɗ',
                 'anterior consonant implosive voiced voiceless': 'ɗ̥',
                 'consonant epiglottal fricative voiced': 'ʢ',
                 'consonant epiglottal fricative voiceless': 'ʜ',
                 'consonant epiglottal stop voiceless': 'ʡ',
                 'affricate consonant glottal voiceless': 'ʔh',
                 'consonant fricative glottal voiced': 'ɦ',
                 'consonant fricative glottal voiceless': 'h',
                 'consonant glottal stop voiceless': 'ʔ',
                 'click consonant labial voiceless': 'ʘ',
                 'click consonant labial voiced voiceless': 'ŋ̊ʘ',
                 'approximant consonant labio-palatal voiced': 'ɥ',
                 'approximant consonant labio-velar voiced': 'w',
                 'approximant consonant labio-velar voiceless': 'ʍ',
                 'consonant fricative labio-dental voiced': 'v',
                 'consonant labio-dental vibrant voiced': 'ⱱ',
                 'affricate consonant labio-dental voiced': 'bv',
                 'approximant consonant labio-dental voiced': 'ʋ',
                 'consonant fricative labio-dental voiced voiceless': 'v̥',
                 'consonant fricative labio-dental voiceless': 'f',
                 'consonant labio-dental nasal voiced': 'ɱ',
                 'consonant labio-dental nasal voiced voiceless': 'ɱ̥',
                 'click consonant lateral voiced': 'gǁ',
                 'click consonant lateral voiceless': 'ǁ',
                 'click consonant lateral voiced voiceless': 'ŋ̊ǁ',
                 'affricate consonant palatal voiced': 'ɟʝ',
                 'affricate consonant palatal voiceless': 'cç',
                 'approximant consonant palatal voiced': 'j',
                 'approximant consonant lateral palatal voiced voiceless': 'ʎ̥',
                 'click consonant palatal voiced': 'gǂ',
                 'click consonant palatal voiceless': 'ǂ',
                 'consonant fricative palatal voiced': 'ʝ',
                 'consonant implosive palatal voiced': 'ʄ',
                 'approximant consonant palatal voiced voiceless': 'j̊',
                 'click consonant palatal voiced voiceless': 'ŋ̊ǂ',
                 'consonant fricative velar voiceless': 'ɧ',
                 'consonant fricative pharyngeal voiced': 'ʕ',
                 'consonant fricative pharyngeal voiceless': 'ħ',
                 'consonant fricative palatal sibilant voiced voiceless': 'ʒ̊',
                 'affricate consonant retroflex sibilant voiceless': 'tʂ',
                 'affricate consonant retroflex sibilant voiced': 'dʐ',
                 'approximant consonant retroflex voiced': 'ɻ',
                 'approximant consonant lateral retroflex voiced': 'ɭ',
                 'approximant consonant lateral retroflex voiced voiceless': 'ɭ̊',
                 'click consonant retroflex voiced': 'gǃǃ',
                 'click consonant retroflex voiceless': 'ǃǃ',
                 'consonant fricative retroflex sibilant voiced': 'ʐ',
                 'consonant fricative retroflex sibilant voiceless': 'ʂ',
                 'consonant nasal retroflex voiced': 'ɳ',
                 'consonant nasal retroflex voiced voiceless': 'ɳ̊',
                 'consonant retroflex stop voiced': 'ɖ',
                 'consonant retroflex stop voiceless': 'ʈ',
                 'consonant retroflex vibrant voiced': 'ɽ',
                 'click consonant retroflex voiced voiceless': 'ŋ̊ǃǃ',
                 'affricate consonant uvular voiced': 'ɢʁ',
                 'affricate consonant uvular voiceless': 'qχ',
                 'approximant consonant uvular voiced': 'ʁ̞',
                 'consonant fricative uvular voiced': 'ʁ',
                 'consonant fricative uvular voiced voiceless': 'ʁ̥',
                 'consonant fricative uvular voiceless': 'ẋ',
                 'consonant implosive uvular voiced': 'ʛ',
                 'consonant implosive uvular voiceless': 'ʠ',
                 'consonant nasal uvular voiced': 'ɴ',
                 'consonant nasal uvular voiced voiceless': 'ɴ̥',
                 'consonant stop uvular voiced': 'ɢ',
                 'consonant stop uvular voiceless': 'q',
                 'consonant uvular vibrant voiced': 'ʀ',
                 'consonant uvular vibrant voiced voiceless': 'ʀ̥',
                 'consonant stop velar voiced': 'g',
                 'consonant stop velar voiceless': 'k',
                 'affricate consonant velar voiced': 'gɣ',
                 'affricate consonant velar voiceless': 'kx',
                 'affricate consonant lateral velar voiceless': 'k\uf268',
                 'approximant consonant velar voiced': 'ɰ',
                 'approximant consonant lateral velar voiced': 'ʟ',
                 'approximant consonant lateral velar voiced voiceless': 'ʟ̥',
                 'consonant fricative velar voiced': 'ɣ',
                 'consonant fricative velar voiced voiceless': 'ɣ̥',
                 'consonant implosive velar voiced': 'ɠ',
                 'consonant nasal velar voiced': 'ŋ',
                 'consonant nasal velar voiced voiceless': 'ŋ̥',
                 'consonant stop velar voiced voiceless': 'g̥',
                 'front open unrounded vowel': 'a',
                 'front open unrounded voiceless vowel': 'ḁ',
                 'front mid unrounded vowel': 'e', 'back open unrounded vowel': 'ɑ',
                 'front mid unrounded voiceless vowel': 'e̥',
                 'front mid rounded vowel': 'e̹', 'close front unrounded vowel': 'i',
                 'close front unrounded voiceless vowel': 'i̥',
                 'close front rounded vowel': 'i̹', 'back mid rounded vowel': 'o',
                 'back mid rounded voiceless vowel': 'o̥',
                 'back close rounded vowel': 'u',
                 'back close rounded voiceless vowel': 'u̥',
                 'central open unrounded vowel': 'ɐ', 'central open rounded vowel': 'ɐ̹',
                 'back open rounded vowel': 'ɒ', 'central mid unrounded vowel': 'ɘ',
                 'central mid rounded vowel': 'ɞ', 'back mid unrounded vowel': 'ɤ',
                 'central close unrounded vowel': 'ɨ', 'back close unrounded vowel': 'ɯ',
                 'back close unrounded voiceless vowel': 'ɯ̥',
                 'front open rounded vowel': 'ɶ', 'central close rounded vowel': 'ʉ',
                 'flat from-low to-low tone': '¹¹',
                 'from-low rising to-mid-low tone': '¹²',
                 'from-low rising to-mid tone': '¹³',
                 'from-low rising to-mid-high tone': '¹⁴',
                 'from-low rising to-high tone': '¹⁵',
                 'falling from-mid-low to-low tone': '²¹',
                 'flat from-mid-low to-mid-low tone': '²²',
                 'from-mid-low rising to-mid tone': '²³',
                 'from-mid-low rising to-mid-high tone': '²⁴',
                 'from-mid-low rising to-high tone': '²⁵',
                 'falling from-mid to-low tone': '³¹',
                 'falling from-mid to-mid-low tone': '³²',
                 'flat from-mid to-mid tone': '³³',
                 'from-mid rising to-mid-high tone': '³⁴',
                 'from-mid rising to-high tone': '³⁵',
                 'falling from-mid-high to-low tone': '⁴¹',
                 'falling from-mid-high to-mid-low tone': '⁴²',
                 'falling from-mid-high to-mid tone': '⁴³',
                 'flat from-mid-high to-mid-high tone': '⁴⁴',
                 'from-mid-high rising to-high tone': '⁴⁵',
                 'falling from-high to-low tone': '⁵¹',
                 'falling from-high to-mid-low tone': '⁵²',
                 'falling from-high to-mid tone': '⁵³',
                 'falling from-high to-mid-high tone': '⁵⁴',
                 'flat from-high to-high tone': '⁵⁵', 'from-low short tone': '¹',
                 'from-mid-low short tone': '²', 'from-mid short tone': '³',
                 'from-mid-high short tone': '⁴', 'from-high short tone': '⁵',
                 'from-low rising to-mid-low tone via-low': '¹¹²',
                 'from-low rising to-mid tone via-low': '¹¹³',
                 'from-low rising to-mid-high tone via-low': '¹¹⁴',
                 'from-low rising to-high tone via-low': '¹¹⁵',
                 'contour from-low to-low tone via-mid-low': '¹²¹',
                 'from-low rising to-mid-low tone via-mid-low': '¹²²',
                 'contour from-low to-low tone via-mid': '¹³¹',
                 'contour from-low to-mid-low tone via-mid': '¹³²',
                 'from-low rising to-mid tone via-mid': '¹³³',
                 'contour from-low to-low tone via-mid-high': '¹⁴¹',
                 'contour from-low to-mid-low tone via-mid-high': '¹⁴²',
                 'contour from-low to-mid tone via-mid-high': '¹⁴³',
                 'from-low rising to-mid-high tone via-mid-high': '¹⁴⁴',
                 'contour from-low to-low tone via-high': '¹⁵¹',
                 'contour from-low to-mid-low tone via-high': '¹⁵²',
                 'contour from-low to-mid tone via-high': '¹⁵³',
                 'contour from-low to-mid-high tone via-high': '¹⁵⁴',
                 'from-low rising to-high tone via-high': '¹⁵⁵',
                 'falling from-mid-low to-low tone via-low': '²¹¹',
                 'contour from-mid-low to-mid-low tone via-low': '²¹²',
                 'contour from-mid-low to-mid tone via-low': '²¹³',
                 'contour from-mid-low to-mid-high tone via-low': '²¹⁴',
                 'contour from-mid-low to-high tone via-low': '²¹⁵',
                 'falling from-mid-low to-low tone via-mid-low': '²²¹',
                 'from-mid-low rising to-mid tone via-mid-low': '²²³',
                 'from-mid-low rising to-mid-high tone via-mid-low': '²²⁴',
                 'from-mid-low rising to-high tone via-mid-low': '²²⁵',
                 'contour from-mid-low to-low tone via-mid': '²³¹',
                 'contour from-mid-low to-mid-low tone via-mid': '²³²',
                 'from-mid-low rising to-mid tone via-mid': '²³³',
                 'contour from-mid-low to-low tone via-mid-high': '²⁴¹',
                 'contour from-mid-low to-mid-low tone via-mid-high': '²⁴²',
                 'contour from-mid-low to-mid tone via-mid-high': '²⁴³',
                 'from-mid-low rising to-mid-high tone via-mid-high': '²⁴⁴',
                 'contour from-mid-low to-low tone via-high': '²⁵¹',
                 'contour from-mid-low to-mid-low tone via-high': '²⁵²',
                 'contour from-mid-low to-mid tone via-high': '²⁵³',
                 'contour from-mid-low to-mid-high tone via-high': '²⁵⁴',
                 'from-mid-low rising to-high tone via-high': '²⁵⁵',
                 'falling from-mid to-low tone via-low': '³¹¹',
                 'contour from-mid to-mid-low tone via-low': '³¹²',
                 'contour from-mid to-mid tone via-low': '³¹³',
                 'contour from-mid to-mid-high tone via-low': '³¹⁴',
                 'contour from-mid to-high tone via-low': '³¹⁵',
                 'falling from-mid to-mid-low tone via-mid-low': '³²²',
                 'contour from-mid to-mid tone via-mid-low': '³²³',
                 'contour from-mid to-mid-high tone via-mid-low': '³²⁴',
                 'contour from-mid to-high tone via-mid-low': '³²⁵',
                 'falling from-mid to-low tone via-mid': '³³¹',
                 'falling from-mid to-mid-low tone via-mid': '³³²',
                 'from-mid rising to-mid-high tone via-mid': '³³⁴',
                 'from-mid rising to-high tone via-mid': '³³⁵',
                 'contour from-mid to-low tone via-mid-high': '³⁴¹',
                 'contour from-mid to-mid-low tone via-mid-high': '³⁴²',
                 'contour from-mid to-mid tone via-mid-high': '³⁴³',
                 'from-mid rising to-mid-high tone via-mid-high': '³⁴⁴',
                 'contour from-mid to-high tone via-mid-high': '³⁴⁵',
                 'contour from-mid to-low tone via-high': '³⁵¹',
                 'contour from-mid to-mid-low tone via-high': '³⁵²',
                 'contour from-mid to-mid tone via-high': '³⁵³',
                 'contour from-mid to-mid-high tone via-high': '³⁵⁴',
                 'from-mid rising to-high tone via-high': '³⁵⁵',
                 'falling from-mid-high to-low tone via-low': '⁴¹¹',
                 'contour from-mid-high to-mid-low tone via-low': '⁴¹²',
                 'contour from-mid-high to-mid tone via-low': '⁴¹³',
                 'contour from-mid-high to-mid-high tone via-low': '⁴¹⁴',
                 'contour from-mid-high to-high tone via-low': '⁴¹⁵',
                 'falling from-mid-high to-mid-low tone via-mid-low': '⁴²²',
                 'contour from-mid-high to-mid tone via-mid-low': '⁴²³',
                 'contour from-mid-high to-mid-high tone via-mid-low': '⁴²⁴',
                 'contour from-mid-high to-high tone via-mid-low': '⁴²⁵',
                 'falling from-mid-high to-mid tone via-mid': '⁴³³',
                 'contour from-mid-high to-mid-high tone via-mid': '⁴³⁴',
                 'contour from-mid-high to-high tone via-mid': '⁴³⁵',
                 'falling from-mid-high to-low tone via-mid-high': '⁴⁴¹',
                 'falling from-mid-high to-mid-low tone via-mid-high': '⁴⁴²',
                 'falling from-mid-high to-mid tone via-mid-high': '⁴⁴³',
                 'from-mid-high rising to-high tone via-mid-high': '⁴⁴⁵',
                 'contour from-mid-high to-low tone via-high': '⁴⁵¹',
                 'contour from-mid-high to-mid-low tone via-high': '⁴⁵²',
                 'contour from-mid-high to-mid tone via-high': '⁴⁵³',
                 'contour from-mid-high to-mid-high tone via-high': '⁴⁵⁴',
                 'from-mid-high rising to-high tone via-high': '⁴⁵⁵',
                 'falling from-high to-low tone via-low': '⁵¹¹',
                 'contour from-high to-mid-low tone via-low': '⁵¹²',
                 'contour from-high to-mid tone via-low': '⁵¹³',
                 'contour from-high to-mid-high tone via-low': '⁵¹⁴',
                 'contour from-high to-high tone via-low': '⁵¹⁵',
                 'falling from-high to-mid-low tone via-mid-low': '⁵²²',
                 'contour from-high to-mid tone via-mid-low': '⁵²³',
                 'contour from-high to-mid-high tone via-mid-low': '⁵²⁴',
                 'contour from-high to-high tone via-mid-low': '⁵²⁵',
                 'falling from-high to-mid tone via-mid': '⁵³³',
                 'contour from-high to-mid-high tone via-mid': '⁵³⁴',
                 'contour from-high to-high tone via-mid': '⁵³⁵',
                 'falling from-high to-mid-high tone via-mid-high': '⁵⁴⁴',
                 'contour from-high to-high tone via-mid-high': '⁵⁴⁵',
                 'falling from-high to-low tone via-high': '⁵⁵¹',
                 'falling from-high to-mid-low tone via-high': '⁵⁵²',
                 'falling from-high to-mid tone via-high': '⁵⁵³',
                 'falling from-high to-mid-high tone via-high': '⁵⁵⁴',
                 'neutral short tone': '⁰', 'marker ¯': '¯', '+ marker': '+',
                 '_ marker': '_', 'marker →': '→', 'marker ←': '←', 'marker ∼': '∼'}

    cache = {}

    def __init__(self, bipa):
        self.bipa = bipa

    def __getitem__(self, item):
        try:
            return self.cache[item]
        except KeyError:
            features = self.features(item)
            feat_str = " ".join(sorted(features))
            coarse_sound = self.coarsened[feat_str]
            self.cache[item] = coarse_sound
            return coarse_sound

    def features(self, item):
        sound = self.bipa[item]
        if sound.type == "unknownsound":
            return set()
        features = set(sound.featureset) - self.remove
        for f in list(features):
            if f in self.change:
                features.remove(f)
                features.add(self.change[f])
        return features
